Accommodate for new Organization-based structure
PostHog/posthog-production pull request #27
Opened 2020-09-09 11:47 UTC by Twixes

This is complimentary to PostHog/posthog#1562. To be merged shortly after the main PR.

2020-09-09 12:09 UTC, Twixes commented
TeamBilling is replaced by OrganizationBilling, but this should be pretty straightforward – the only difference is mapping 1-to-1 to Organization instead of Team. Slight hurdle: will only be able to write a migration for this after changes get merged in the main repo.

2020-09-24 11:20 UTC, fuziontech requested changes
quick look before passing this to Paulo. Looks like cls is used where it might not be a classmethod?

2020-09-24 11:20 UTC, fuziontech commented on README.md
> +# PostHog Cloud
💯

2020-09-24 11:20 UTC, fuziontech commented on messaging/tests/test_messaging.py
> +            company_name="Test", email="test@posthog.com", password=None, first_name="John Test"
Doesn't this need to be decorated as a `@classmethod` to use `cls`? otherwise `cls` will really be `self` which is super confusing.

2020-09-24 11:22 UTC, Twixes commented on messaging/tests/test_messaging.py
> +            company_name="Test", email="test@posthog.com", password=None, first_name="John Test"
Good catch

2020-09-24 12:14 UTC, paolodamico commented on multi_tenancy/tests/test_billing.py
> +            checkout_session_created_at=timezone.now() - timezone.timedelta(hours=23),
Any reason to replace `datetime` with `timezone`? It's the [same imported object](https://github.com/django/django/blob/e26a7a8ef41f0d69951affb21655cdc2cf94a209/django/utils/timezone.py#L7)

2020-09-24 12:14 UTC, paolodamico commented on package.json
>    "license": "ISC",
Taking advantage of this update we should change this. The repo is fully copyrighted, no ISC license.

2020-09-24 12:16 UTC, Twixes commented on multi_tenancy/tests/test_billing.py
> +            checkout_session_created_at=timezone.now() - timezone.timedelta(hours=23),
No particular reason, just consistency

2020-09-24 12:19 UTC, Twixes commented on latest_migrations.manifest
> +ee: 0002_hook
Not sure, but also I don't think this file actually does anything in this repo 🤔

2020-09-24 12:21 UTC, paolodamico commented on latest_migrations.manifest
> +ee: 0002_hook
Haven't seen it before 🤷‍♂️, did something change that started generating it in this repo?

2020-09-24 12:26 UTC, Twixes commented on multi_tenancy/models.py
> +class OrganizationBilling(models.Model):
I decided to go with a new model to have `organization` be the primary key (a bit wonky to migrate otherwise). The migration does copy data over to the new model.

2020-09-24 12:34 UTC, paolodamico commented on multi_tenancy/models.py
> +class OrganizationBilling(models.Model):
Ok cool 👍

2020-09-24 12:45 UTC, Twixes commented on latest_migrations.manifest
> +ee: 0002_hook
🤷‍♂️ No idea. I deleted it.

2020-09-24 12:49 UTC, merged