Usage-based pricing base support
PostHog/posthog-production pull request #53
Opened 2020-12-08 00:29 UTC by paolodamico

Lays the ground work to support usage-based (metered) pricing.

- Introduces the MonthlyBillingRecord to store usage information.
- Allows creating tiered-based subscriptions. These are handled separately from standard subscriptions. The initial process (the checkout session) only creates a session to set up payment information for future billing. After payment information has been set, on the received webhook a usage-based subscription is created.
    - Introduces `is_metered_billing` attribute to `Plan` to identify such plans.

In addition, this PR:
- Removes repeated tests.
- Refactors the `create_checkout_session` method for more clarity.
- Refactors the webhook tests to avoid having almost all tests in a single file which makes them hard to read and maintain.

### Additional notes
- Support for monthly flat-fee plans is maintained.
    - The above includes full support for the startup plan.﻿

2020-12-08 22:53 UTC, paolodamico commented
CC @timgl in case you want to review

2020-12-09 08:51 UTC, Twixes requested changes
Looks good! Only please give the migration a meaningful name.

2020-12-09 08:51 UTC, Twixes commented on multi_tenancy_settings.py
> +# https://github.com/posthog/posthog-production
What's the link for?

2020-12-09 15:13 UTC, paolodamico commented on multi_tenancy_settings.py
> +# https://github.com/posthog/posthog-production
Good catch, documented the `posthog-production` environment variables on the README now.

2020-12-09 15:21 UTC, merged