Cloud billing improvements
PostHog/posthog-production pull request #69
Opened 2021-02-04 10:52 UTC by paolodamico

Complimentary PR to https://github.com/PostHog/posthog/pull/3192.

- Register Stripe customer portal usage through PostHog.
- Introduce default event allocation for when organizations have not yet set up billing. Please check the readme for details on how this configuration works.

2021-02-08 12:24 UTC, Twixes requested changes

2021-02-08 12:24 UTC, Twixes commented on README.md
> +[slack]: https://posthog.com/slack?utm_medium=readme&utm_campaign=posthog-production&utm_source=github.com
Why so?

2021-02-08 12:24 UTC, Twixes commented on multi_tenancy/migrations/0009_auto_20210204_1216.py
> +# Generated by Django 3.0.11 on 2021-02-04 12:16
Migration should have a meaningful name.

2021-02-08 12:24 UTC, Twixes commented on multi_tenancy/models.py
> +    )  # A human-friendly representation of the price of the plan to show on the front-end UI.
Curious: why is this stored here and why is it a string?

2021-02-08 12:24 UTC, Twixes commented on multi_tenancy/models.py
> +            "formatted": compact_number(self.event_allowance),
We should not format numbers on the model.

2021-02-08 12:24 UTC, Twixes commented on multi_tenancy/models.py
> +                return None
Won't this cause `None` to be returned both if `BILLING_NO_PLAN_EVENT_ALLOCATION` is `None` and if it's `0`?

2021-02-08 12:24 UTC, Twixes commented on multi_tenancy/models.py
> +                "formatted": compact_number(no_plan_event_allocation),
Formatting on model verboten

2021-02-08 15:09 UTC, paolodamico commented on README.md
> +[slack]: https://posthog.com/slack?utm_medium=readme&utm_campaign=posthog-production&utm_source=github.com
Well the UTM tags is so that we can track where the user signed up from, separated the link in the end so it's a bit more clean.

2021-02-08 15:10 UTC, paolodamico commented on multi_tenancy/models.py
> +    )  # A human-friendly representation of the price of the plan to show on the front-end UI.
It is just so that we can provide this information in the UI without the user having to go to posthog.com/pricing. Ideally in the future we would get this information from Stripe, but right now it's not worth the effort. We would have to both proxy the information, plus add some complex parsing logic to support the multiple plan scenarios that we could have.

2021-02-08 15:11 UTC, paolodamico commented on multi_tenancy/models.py
> +            "formatted": compact_number(self.event_allowance),
While I don't think it's as clear cut, because this would require having now the exact same logic duplicated both on the FE & BE (because we use the same formatter on emails), I would like to leave this to a separate PR as it'll require updating both repos at the same time. Sounds good?

2021-02-08 15:18 UTC, Twixes commented on README.md
> +[slack]: https://posthog.com/slack?utm_medium=readme&utm_campaign=posthog-production&utm_source=github.com
Makes sense, though I liked the full line-link-subheading format a bit more

2021-02-08 15:25 UTC, Twixes commented on multi_tenancy/models.py
> +            "formatted": compact_number(self.event_allowance),
Alright! I'd very much prefer to have an analogous function on the frontend for this, especially since this isn't complex logic and it doesn't have to match up 100% in all edge cases.

2021-02-09 08:55 UTC, paolodamico commented on multi_tenancy/models.py
> +            "formatted": compact_number(self.event_allowance),
Sounds good! Will do this in a separate PR set.

2021-02-09 08:56 UTC, paolodamico commented on multi_tenancy/models.py
> +                return None
Great catch, fixed!

2021-02-09 09:01 UTC, paolodamico commented
Feedback addressed, @Twixes would you mind taking another quick look so I can merge? I discussed the topic of the description plan with @macobo, and as I wanted us to be able to do some extra formatting other than just the plain text (e.g. bold words), we came up with this option of storing the plan details as HTML on this repo and then fetching it in the FE. This way we can have complex formatting without the strong risks of setting inner HTML from the DB.

2021-02-09 09:10 UTC, Twixes approved these changes

2021-02-09 09:31 UTC, merged