Add PostHog token cookie middleware
PostHog/posthog-production pull request #70
Opened 2021-02-08 16:16 UTC by yakkomajuri

Adds 2 new cookies that will be used to autofill the user's token in our docs if they're authenticated into Cloud.

- `ph_current_project_token`
- `ph_current_project_name`

Both are needed because given that we now have multiple projects, it'll be important to show the user a tooltip saying what project's token this is.

2021-02-09 13:58 UTC, paolodamico commented on multi_tenancy/tests/test_middleware.py
> +        self.client.force_login(self.user)
This test case seem duplicated

2021-02-09 14:07 UTC, paolodamico commented on multi_tenancy/middleware.py
> +    'samesite': "Lax",  # can't be set to "None" here
I think we could do `Strict` here

2021-02-09 14:09 UTC, paolodamico commented on multi_tenancy/middleware.py
> +    'httponly': True,
While this is certainly more secure, wouldn't you need to access the cookie on the client-side to show it on the docs page?

2021-02-09 14:11 UTC, paolodamico commented on multi_tenancy/middleware.py
> +    'domain': None,
Maybe worth explicitly setting this for `posthog.com`?

2021-02-09 14:12 UTC, paolodamico requested changes

2021-02-09 14:12 UTC, paolodamico commented on multi_tenancy/middleware.py
> +        if request.path.startswith("/api/") or request.path.startswith("/e/") or request.path.startswith("/decide/"):
Actually, it's important to remove the trailing slash, as the endpoints may or may not have it. In addition, I believe you're at least missing `/batch`, `/track`, `/capture` & `/s`

2021-02-09 15:25 UTC, yakkomajuri commented
Great points - a lot of the basics here came from the toolbar cookies and indeed the toolbar needs much more liberal settings than this. Will update!

2021-02-10 13:46 UTC, yakkomajuri commented
@paolodamico ready for another go

2021-02-15 14:57 UTC, paolodamico approved these changes

2021-02-15 15:23 UTC, merged